separator: "----"
index_start: 1
index_format: "{item_index}: {item_name}"
numbered: True
groups:
- items:
  - name: Built-in only
    command: ~/.config/scripts/rofimonitor.sh built-in
  - name: HDMI and Built-in
    command: ~/.config/scripts/rofimonitor.sh hdmi
  - name: HDMI only
    command: ~/.config/scripts/rofimonitor.sh only-hdmi
  - name: VGA and Built-in
    command: ~/.config/scripts/rofimonitor.sh vga
  - name: VGA only
    command: ~/.config/scripts/rofimonitor.sh only-vga

