#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal

# Source generated colors.
source "${HOME}/.cache/wal/colors.sh"

reload_dunst() {
    pkill dunst
    dunst \
        -lb "${color1}" \
        -nb "${color1}" \
        -cb "${color1}" \
        -lf "${color15}" \
        -bf "${color15}" \
        -cf "${color15}" \
        -nf "${color6}" \
	-lfr "${color2}" \
	-nfr "${color2}" \
	-cfr "${color2}" &
}
reload_dunst
